### ISSUE TITLE
Oh, it looks good, but how does it work?

### ISSUE THREAD

**Issue by BrightMoonInner** [Licsber/notice#1]
What happened? What should I do?Could you help me please?
![日志](https://user-images.githubusercontent.com/88758484/131819748-7de75f65-4602-4c1a-b7ca-16145b402579.jpg)

**Comment by licsber** [comment]
Sorry, but this log may not belong to this project, do you make something wrong?
Maybe turn to others for help.

**Comment by BrightMoonInner** [comment]
Okay,  I see, thank you for your reply.
